In [3]:
v=np.linspace(0,10,5)
v

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [2]:
import numpy as np

In [4]:
print(v)
v2=v[2:4].copy()
print(v2)
v2[0]=55
print(v,v2)

[ 0.   2.5  5.   7.5 10. ]
[5.  7.5]
(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), array([55. ,  7.5]))


In [10]:
print(v)
v2=v[2:4]
print(v2)
v2=12
print(v,v2)

[ 0.   2.5  5.   7.5 10. ]
[5.  7.5]
(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 12)


In [ ]:
# filtering data

In [11]:
v=np.linspace(0,10,6)
v

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [12]:
print(v)
v1=v[[1,4]]
print(v1)

[ 0.  2.  4.  6.  8. 10.]
[2. 8.]


In [13]:
v>0

array([False,  True,  True,  True,  True,  True])

In [22]:
bool_ind=v>2


In [27]:
v[bool_ind]

IndexError: list index out of range

In [25]:
vv=np.random .random((5,4))
vv

array([[0.04993596, 0.21668309, 0.65757049, 0.72283219],
       [0.25104349, 0.09373215, 0.37432489, 0.36231225],
       [0.36005475, 0.47361187, 0.13346066, 0.01950669],
       [0.42932807, 0.87842117, 0.60551997, 0.86053587],
       [0.38841437, 0.07892954, 0.44542915, 0.21111532]])

In [26]:
print(vv)
vv[vv>.5]

[[0.04993596 0.21668309 0.65757049 0.72283219]
 [0.25104349 0.09373215 0.37432489 0.36231225]
 [0.36005475 0.47361187 0.13346066 0.01950669]
 [0.42932807 0.87842117 0.60551997 0.86053587]
 [0.38841437 0.07892954 0.44542915 0.21111532]]


array([0.65757049, 0.72283219, 0.87842117, 0.60551997, 0.86053587])

In [28]:
vv[vv>.5]=1
vv

array([[0.04993596, 0.21668309, 1.        , 1.        ],
       [0.25104349, 0.09373215, 0.37432489, 0.36231225],
       [0.36005475, 0.47361187, 0.13346066, 0.01950669],
       [0.42932807, 1.        , 1.        , 1.        ],
       [0.38841437, 0.07892954, 0.44542915, 0.21111532]])

In [31]:
vals=np.array([1,2,5,6,4,8,9])
print(vals)
np.where(vals%3==0)

[1 2 5 6 4 8 9]


(array([3, 6], dtype=int64),)

In [32]:
vals_new=np.where(vals%3==0,-1,vals*2)
vals_new

array([ 2,  4, 10, -1,  8, 16, -1])

In [33]:
#exercise
data=np.array([range(5),range(5,10),range(10,15),range(15,20)])
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [38]:
#display all odd number
data[data%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [52]:
#display all even number
even=np.where(data%2==0,-1,data)
even

array([-1,  3, -1,  9, -1, 15, -1, 21, -1, 27, -1, 33, -1, 39, -1, 45, -1,
       51, -1, 57, -1, 63, -1, 69, -1, 75, -1, 81, -1, 87, -1, 93, -1, 99])

In [53]:
data=np.arange(0,100,3)
data[(data%2==0)|(data%9==0)]

array([ 0,  6,  9, 12, 18, 24, 27, 30, 36, 42, 45, 48, 54, 60, 63, 66, 72,
       78, 81, 84, 90, 96, 99])

In [54]:
#some additional snippets
data=np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=float)
data

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [55]:
data[:,1:4]

array([[2., 3., 4.],
       [7., 8., 9.]])

In [56]:
data[::-1]

array([[ 6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.]])

In [57]:
data[:,::-1]

array([[ 5.,  4.,  3.,  2.,  1.],
       [10.,  9.,  8.,  7.,  6.]])

In [64]:
#reverse columns and rows
data[::-1,::-1]

array([[10.,  9.,  8.,  7.,  6.],
       [ 5.,  4.,  3.,  2.,  1.]])

In [65]:
#reshaping
reshape=data.reshape((5,2))
reshape

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [67]:
flattend=data.flatten()
flattend

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [68]:
#generating random 
np.random.rand(3,3)


array([[0.18144397, 0.50751183, 0.85140367],
       [0.36000697, 0.79609366, 0.71124598],
       [0.60508169, 0.72809501, 0.27109786]])

In [69]:
np.random.randint(0,10,(5,5))

array([[1, 9, 7, 4, 4],
       [9, 7, 5, 5, 7],
       [8, 8, 5, 5, 8],
       [4, 4, 9, 4, 8],
       [7, 6, 5, 9, 6]])

In [70]:
np.random.choice(['china','us','india','canada'],(3,4))

array([['india', 'china', 'india', 'us'],
       ['china', 'canada', 'india', 'china'],
       ['us', 'canada', 'china', 'canada']], dtype='|S6')

In [75]:
np.random.seed(15)
np.random.choice(['china','us','india','canada'],(3,4))

array([['china', 'us', 'china', 'us'],
       ['canada', 'china', 'china', 'canada'],
       ['canada', 'canada', 'us', 'india']], dtype='|S6')

In [ ]:
#vectorize
