In [1]:
import numpy as np

In [3]:
v=np.linspace(0,12,5)
v

array([ 0.,  3.,  6.,  9., 12.])

In [4]:
v[0],v[1],v[-1]

(0.0, 3.0, 12.0)

In [6]:
v[2:5]

array([ 6.,  9., 12.])

In [7]:
vv=np.random .random((5,4))
vv

array([[0.37141624, 0.86720145, 0.86658137, 0.39184137],
       [0.35423418, 0.82894275, 0.31893675, 0.56450479],
       [0.05917706, 0.93968732, 0.28407903, 0.37640124],
       [0.16203755, 0.5485143 , 0.21503501, 0.91068907],
       [0.76245533, 0.89209312, 0.31467568, 0.78064228]])

In [8]:
vv[0][0]

0.3714162442198172

In [12]:
vv[0,0],vv[4,3]

(0.3714162442198172, 0.7806422805963268)

In [14]:
l=[[1,2,3],[2,5,6]]
l[0][2]

3

In [17]:
vv

array([[0.37141624, 0.86720145, 0.86658137, 0.39184137],
       [0.35423418, 0.82894275, 0.31893675, 0.56450479],
       [0.05917706, 0.93968732, 0.28407903, 0.37640124],
       [0.16203755, 0.5485143 , 0.21503501, 0.91068907],
       [0.76245533, 0.89209312, 0.31467568, 0.78064228]])

In [18]:
vv[2:5,1]

array([0.93968732, 0.5485143 , 0.89209312])

In [20]:
vv[2:5,0:2]

array([[0.05917706, 0.93968732],
       [0.16203755, 0.5485143 ],
       [0.76245533, 0.89209312]])