In [1]:
#indexing and slicing
import numpy as np
v=np.linspace(0,10,5)
v

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [2]:
v[0],v[1],v[-1]

(0.0, 2.5, 10.0)

In [3]:
v[2:4]#Right exclusion

array([5. , 7.5])

In [4]:
vv=np.random.random((5,4))
vv

array([[0.13682218, 0.17329953, 0.23987755, 0.28585046],
       [0.17282505, 0.65943834, 0.82509698, 0.44619915],
       [0.83138044, 0.42129294, 0.12457145, 0.99586747],
       [0.71694123, 0.49750148, 0.37518291, 0.89940403],
       [0.60802149, 0.08941664, 0.3248018 , 0.32525697]])

In [5]:
vv[0][0]

0.13682217901092952

In [6]:
vv[0,0],vv[4,3]#It's only possible in numpy not in list ie., v[0][0] as v[0,0]

(0.13682217901092952, 0.32525696508084734)

In [7]:
ll=[[1,2,3],[4,5,6]]
ll[0][1]

2

In [8]:
vv

array([[0.13682218, 0.17329953, 0.23987755, 0.28585046],
       [0.17282505, 0.65943834, 0.82509698, 0.44619915],
       [0.83138044, 0.42129294, 0.12457145, 0.99586747],
       [0.71694123, 0.49750148, 0.37518291, 0.89940403],
       [0.60802149, 0.08941664, 0.3248018 , 0.32525697]])

In [9]:
vv[2:5,1]#IT will stretch the data won't give in vertical formate
#Row 2 to 5-1 and coloumn 2

array([0.42129294, 0.49750148, 0.08941664])

In [10]:
vv[2:5,0:3]

array([[0.83138044, 0.42129294, 0.12457145],
       [0.71694123, 0.49750148, 0.37518291],
       [0.60802149, 0.08941664, 0.3248018 ]])

In [11]:
##Copying numpy objects
v=np.linspace(0,10,5)
v

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
print(v)
v2=v[2:4]
print(v2)
v2[0]=55#This is shallowcopy if we change the value in the subset retrived and made any change that will reflect in the orginal copy if we don't want this to happen use copy() function to have a deep copy
#Sallow copy uses the same memory space v2 is the pointer used to point v
print(v,v2)#Here the value 55 is changed in v also

[ 0.   2.5  5.   7.5 10. ]
[5.  7.5]
(array([ 0. ,  2.5, 55. ,  7.5, 10. ]), array([55. ,  7.5]))


In [13]:
print(v)
v2=v[2:4].copy()
print(v2)
v2[0]=55#This is shallowcopy if we change the value in the subset retrived and made any change that will reflect in the orginal copy if we don't want this to happen use copy() function to have a deep copy
#Shallow copy uses the same memory space v2 is the pointer used to point v
print(v,v2)#here v2 is deep copy it will have another memory that won't change value in v

[ 0.   2.5 55.   7.5 10. ]
[55.   7.5]
(array([ 0. ,  2.5, 55. ,  7.5, 10. ]), array([55. ,  7.5]))


In [14]:
#Filtering data
v=np.linspace(0,10,5)#Used to generate a number from 0 to 10 in 5 equal parts
v


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
print(v)
v1=v[[1,3]]#list inside the bracket that list contains value frpm 1 to 3
print(v1)

[ 0.   2.5  5.   7.5 10. ]
[2.5 7.5]


In [16]:
v>0#Relational operations are possible in numpy array that will return boolean value

array([False,  True,  True,  True,  True])

In [17]:
bool_ind=v>5#returns value >5
v[bool_ind] #numpy array v[condition]

array([ 7.5, 10. ])

In [18]:
print(vv)
vv[vv>0.5]#numpy array vv[condition]

[[0.13682218 0.17329953 0.23987755 0.28585046]
 [0.17282505 0.65943834 0.82509698 0.44619915]
 [0.83138044 0.42129294 0.12457145 0.99586747]
 [0.71694123 0.49750148 0.37518291 0.89940403]
 [0.60802149 0.08941664 0.3248018  0.32525697]]


array([0.65943834, 0.82509698, 0.83138044, 0.99586747, 0.71694123,
       0.89940403, 0.60802149])

In [19]:
vv[vv>.5]=1#returns the "value" 1 if value in vv > 5
vv

array([[0.13682218, 0.17329953, 0.23987755, 0.28585046],
       [0.17282505, 1.        , 1.        , 0.44619915],
       [1.        , 0.42129294, 0.12457145, 1.        ],
       [1.        , 0.49750148, 0.37518291, 1.        ],
       [1.        , 0.08941664, 0.3248018 , 0.32525697]])

In [20]:
vals=np.array([1,2,3,4,5,6,7,8,9,10])
print(vals)
np.where(vals%3==0)#This will return the "index" where value %3==0



[ 1  2  3  4  5  6  7  8  9 10]


(array([2, 5, 8], dtype=int64),)

In [21]:
vals_new=np.where(vals%2==0,-1,vals*10)#i's like if else
#np.where(condition,if true statement,if false)
vals_new

array([10, -1, 30, -1, 50, -1, 70, -1, 90, -1])

In [22]:
#Display all odd number in data
#Replace all even numbers in data with -1

data=np.array([range(5),range(5,10),range(10,15),range(15,20)])#2-D array
#data
data[data%2 !=0]
data[data%2==0]=-1
data



array([[-1,  1, -1,  3, -1],
       [ 5, -1,  7, -1,  9],
       [-1, 11, -1, 13, -1],
       [15, -1, 17, -1, 19]])

In [23]:
data=np.arange(0,100,3)
data
#Display all values that are multiples of a or multiples of 9
#Wrong: data[data%2==0 or data%9==0,data] here and and or won't work 
#instead use &,| respectively
#while using more than one condition use brackets else it won't work
data[(data%2==0)|(data%9==0)]


array([ 0,  6,  9, 12, 18, 24, 27, 30, 36, 42, 45, 48, 54, 60, 63, 66, 72,
       78, 81, 84, 90, 96, 99])

In [54]:
#some array function to reverse
import numpy as np
data=np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=np.float)
data

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [55]:
data[:,1:4]#All rows bt specified coloumn

array([[2., 3., 4.],
       [7., 8., 9.]])

In [57]:
data[::-1]#used to "reverse rows" that is lat will be in first, and so on and 1st will be in last

array([[ 6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.]])

In [59]:
data[:,::-1]#used to reverse coloumn

array([[ 5.,  4.,  3.,  2.,  1.],
       [10.,  9.,  8.,  7.,  6.]])

In [62]:
#reverse both row and columns of data
#Output sould be like
data[::-1,::-1]#both row and column reverse

array([[10.,  9.,  8.,  7.,  6.],
       [ 5.,  4.,  3.,  2.,  1.]])

In [64]:
#Infinity as inf
#not a number as nan
data[0,0]=np.inf
data[-1,-1]=np.nan
data

array([[inf,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., nan]])

In [66]:
#Reshapping
reshaped=data.reshape((5,2))
reshaped

array([[inf,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., nan]])

In [67]:
flattened=data.flatten()
flattened

array([inf,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., nan])

In [69]:
#generating random numbers
np.random.rand(3,3)#(dimensions that is rows and columns)

array([[0.68414237, 0.64838673, 0.11045804],
       [0.20039885, 0.86366242, 0.15219734],
       [0.21685271, 0.89674212, 0.23286887]])

In [70]:
np.random.randint(0,10,(5,5))

array([[4, 3, 0, 0, 8],
       [6, 0, 9, 4, 2],
       [6, 6, 2, 1, 5],
       [3, 3, 0, 9, 4],
       [3, 0, 5, 2, 8]])

In [73]:
np.random.choice(["india","china","srilanka","uk","us"],(3,4))
#Choice(data,(dimension))

array([['us', 'uk', 'china', 'us'],
       ['srilanka', 'china', 'china', 'srilanka'],
       ['china', 'china', 'china', 'srilanka']], dtype='<U8')

In [24]:
#Seed(any integer) function is used to generate a standard random number that won't get change
#when we run any number of times if we change the integer value in seed(value) it will change once 
np.random.seed(5)
np.random.choice(["india","china","srilanka","uk","us"],(3,4))

array([['uk', 'india', 'china', 'india'],
       ['us', 'uk', 'india', 'india'],
       ['us', 'china', 'india', 'uk']], dtype='|S8')

In [25]:
#Vectors
def calc(a):
    if(a%2==0):
        return(a**2)
    else:
        return(a-1)
    


In [77]:
vals=np.array([1,2,3,4,5])
calc(vals[1])#we cant pass the whole array as an argument to a function so that we use vectorize() fun

4

In [79]:
calc(val)

NameError: name 'val' is not defined

In [80]:
v_calc=np.vectorize(calc)
v_calc(vals)

array([ 0,  4,  2, 16,  4])

In [81]:
#create a function that converts the number to its binary format
#use vecorze to apply it on a numpy array

In [82]:
bin(20)

'0b10100'

In [84]:
"""Records using hetrogeneous datatypes"""
rec=np.array([(1,(98.5,96),"ram"),(2,(100,76.9),"raj")], dtype=[('RollNo',np.int32),('mark',np.float64,2),('Name',np.str,4)])

In [85]:
rec

array([(1, [ 98.5,  96. ], 'ram'), (2, [100. ,  76.9], 'raj')],
      dtype=[('RollNo', '<i4'), ('mark', '<f8', (2,)), ('Name', '<U4')])

In [87]:
rec[0]

(1, [98.5, 96. ], 'ram')

In [89]:
rec['Name']

array(['ram', 'raj'], dtype='<U4')

In [92]:
rec[0]['mark']

array([98.5, 96. ])

In [94]:
rec['mark'][0]

array([98.5, 96. ])

In [99]:
#Schemas are used to specify the type and the name of the data available in file
schema=np.dtype([('Year',np.float16),
                ('month',np.float16),
                ('day',np.float16),
                ('hour',np.float16),
                ('minute',np.float16),
                ('temp',np.float16)])
np_data=np.loadtxt('weather1week.csv',dtype=schema,delimiter=';')
np_data

array([(2018., 9.,  9.,  0., 0., 22.64), (2018., 9.,  9.,  1., 0., 22.42),
       (2018., 9.,  9.,  2., 0., 22.3 ), (2018., 9.,  9.,  3., 0., 22.2 ),
       (2018., 9.,  9.,  4., 0., 22.14), (2018., 9.,  9.,  5., 0., 22.2 ),
       (2018., 9.,  9.,  6., 0., 23.39), (2018., 9.,  9.,  7., 0., 24.42),
       (2018., 9.,  9.,  8., 0., 24.7 ), (2018., 9.,  9.,  9., 0., 24.6 ),
       (2018., 9.,  9., 10., 0., 24.14), (2018., 9.,  9., 11., 0., 23.95),
       (2018., 9.,  9., 12., 0., 23.9 ), (2018., 9.,  9., 13., 0., 23.28),
       (2018., 9.,  9., 14., 0., 23.27), (2018., 9.,  9., 15., 0., 25.42),
       (2018., 9.,  9., 16., 0., 25.75), (2018., 9.,  9., 17., 0., 24.19),
       (2018., 9.,  9., 18., 0., 23.48), (2018., 9.,  9., 19., 0., 22.94),
       (2018., 9.,  9., 20., 0., 22.48), (2018., 9.,  9., 21., 0., 22.11),
       (2018., 9.,  9., 22., 0., 22.1 ), (2018., 9.,  9., 23., 0., 22.06),
       (2018., 9., 10.,  0., 0., 22.05), (2018., 9., 10.,  1., 0., 22.02),
       (2018., 9., 10.,  

In [100]:
np_data[0]

(2018., 9., 9., 0., 0., 22.64)

In [101]:
np_data['temp']

array([22.64, 22.42, 22.3 , 22.2 , 22.14, 22.2 , 23.39, 24.42, 24.7 ,
       24.6 , 24.14, 23.95, 23.9 , 23.28, 23.27, 25.42, 25.75, 24.19,
       23.48, 22.94, 22.48, 22.11, 22.1 , 22.06, 22.05, 22.02, 22.  ,
       22.  , 22.02, 22.05, 21.48, 24.08, 25.7 , 26.34, 26.92, 25.27,
       24.69, 25.48, 24.05, 23.95, 23.7 , 23.11, 22.72, 22.6 , 22.5 ,
       22.36, 22.23, 22.05, 21.89, 21.77, 21.69, 21.66, 21.62, 21.6 ,
       21.62, 23.94, 25.27, 26.47, 27.58, 26.95, 26.45, 25.56, 24.61,
       24.11, 23.77, 23.72, 23.12, 22.95, 22.86, 22.7 , 22.75, 22.77,
       22.61, 22.45, 22.48, 22.55, 22.31, 22.16, 22.66, 25.12, 26.53,
       26.2 , 26.39, 28.31, 27.53, 28.44, 29.23, 28.23, 27.92, 27.17,
       25.2 , 24.12, 23.44, 23.19, 23.2 , 23.22, 23.42, 23.6 , 23.83,
       23.47, 23.19, 22.27, 21.75, 23.56, 23.69, 24.86, 26.52, 28.23,
       27.73, 27.4 , 26.94, 26.6 , 26.36, 26.55, 25.11, 24.05, 23.5 ,
       23.4 , 23.52, 23.6 , 23.55, 23.3 , 23.05, 22.88, 22.69, 22.5 ,
       22.56, 24.73,

In [102]:
np_data[0]["day"]

9.0

In [106]:
#Converting celscius to farheat in file weather1week 
np_data['temp']=np_data['temp']*(9/5)+32
np_data


array([(2018., 9.,  9.,  0., 0., 617.5), (2018., 9.,  9.,  1., 0., 615. ),
       (2018., 9.,  9.,  2., 0., 613.5), (2018., 9.,  9.,  3., 0., 613.5),
       (2018., 9.,  9.,  4., 0., 612.5), (2018., 9.,  9.,  5., 0., 613.5),
       (2018., 9.,  9.,  6., 0., 625.5), (2018., 9.,  9.,  7., 0., 636.5),
       (2018., 9.,  9.,  8., 0., 639. ), (2018., 9.,  9.,  9., 0., 637.5),
       (2018., 9.,  9., 10., 0., 633. ), (2018., 9.,  9., 11., 0., 631.5),
       (2018., 9.,  9., 12., 0., 630.5), (2018., 9.,  9., 13., 0., 624. ),
       (2018., 9.,  9., 14., 0., 624. ), (2018., 9.,  9., 15., 0., 646. ),
       (2018., 9.,  9., 16., 0., 650. ), (2018., 9.,  9., 17., 0., 633.5),
       (2018., 9.,  9., 18., 0., 626. ), (2018., 9.,  9., 19., 0., 620.5),
       (2018., 9.,  9., 20., 0., 616. ), (2018., 9.,  9., 21., 0., 611.5),
       (2018., 9.,  9., 22., 0., 611.5), (2018., 9.,  9., 23., 0., 611.5),
       (2018., 9., 10.,  0., 0., 611. ), (2018., 9., 10.,  1., 0., 610.5),
       (2018., 9., 10.,  

In [ ]:
#