In [4]:
import numpy as np
print(np.__version__)

1.15.4


In [6]:
a=np.array([1,2,3,8,9])
a

array([1, 2, 3, 8, 9])

In [7]:
a=np.array([1,2.5,3,6,9])
a

array([1. , 2.5, 3. , 6. , 9. ])

In [11]:
a=np.array([1,2,3,4,6])
newstrarray=a.astype(str)
newstrarray

array(['1', '2', '3', '4', '6'], dtype='|S11')

In [12]:
help(a.astype)

Help on built-in function astype:

astype(...)
    a.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)
    
    Copy of the array, cast to a specified type.
    
    Parameters
    ----------
    dtype : str or dtype
        Typecode or data-type to which the array is cast.
    order : {'C', 'F', 'A', 'K'}, optional
        Controls the memory layout order of the result.
        'C' means C order, 'F' means Fortran order, 'A'
        means 'F' order if all the arrays are Fortran contiguous,
        'C' order otherwise, and 'K' means as close to the
        order the array elements appear in memory as possible.
        Default is 'K'.
    casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
        Controls what kind of data casting may occur. Defaults to 'unsafe'
        for backwards compatibility.
    
          * 'no' means the data types should not be cast at all.
          * 'equiv' means only byte-order changes are allowed.
          * 'safe' means o

In [13]:
newstrarray.tolist()

['1', '2', '3', '4', '6']

In [21]:
a=np.array([1,2,3,4,5],dtype=np.float64)
a

array([1., 2., 3., 4., 5.])

In [17]:
a.ndim,a.shape,a.size

(1, (5L,), 5)

In [51]:
a=np.array(range(0,50))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [48]:
a=np.array([[1,2,3,4,5],[1,2,3,5]])
a.tolist()
a.ndim,a.shape

(1, (2L,))

In [56]:
def meta(a):
    print(a.ndim,a.shape,a.size)
meta(a)


(1, (50L,), 50)


In [58]:
sample=np.array([1,"vicky",98])
sample

array(['1', 'vicky', '98'], dtype='|S11')

In [61]:
sample=np.array([1,"vicky",99],dtype=np.object)
sample

array([1, 'vicky', 99], dtype=object)

In [62]:
l=[1,2,3,4]
npa=np.array(l)
l,npa

([1, 2, 3, 4], array([1, 2, 3, 4]))

In [63]:
l+2

TypeError: can only concatenate list (not "int") to list

In [64]:
npa+2

array([3, 4, 5, 6])

In [80]:
totallist=np.random.randint(200,500,10)
totallist=totallist*100/500
totallist


array([97, 81, 45, 83, 55, 69, 54, 73, 54, 48])

In [92]:
s=np.array([[1,2,3,4,5,4],[6,8,9,5,4,1]])
s

array([[1, 2, 3, 4, 5, 4],
       [6, 8, 9, 5, 4, 1]])

In [93]:
s[1][1]

8

In [94]:
s.ndim,s.shape,s.size,s.dtype

(2, (2L, 6L), 12, dtype('int32'))

In [103]:
x=np.array([[[1,2,3,5],[1,2,3,7],[1,5,6,7],[1,2,5,6],[5,6,8,7]],[[1,2,3,5],[1,2,3,7],[1,5,6,7],[1,2,5,6],[5,6,8,7]],[[1,2,3,5],[1,2,3,7],[1,5,6,7],[1,2,5,6],[5,6,8,7]]])
x.shape

(3L, 5L, 4L)

In [104]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [105]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [106]:
start=0
end=10
step=5
np.linspace(start,end,step)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [107]:
start=0
end=10
step=.2
np.arange(start,end,step)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])